# Generated by Django 4.1.3 on 2022-11-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_num', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=50)),
                ('marks', models.IntegerField(max_length=3)),
            ],
        ),
    ]
